name: Automated update

on:
  schedule:
    - cron:  '0 0,12 * * *'

jobs:
  update:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Update repository
      run: ./update.sh
