name: Automated update

on:
  schedule:
    - cron:  '0 0,12 * * *'

jobs:
  update:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    
    - name: Setup git
      run: |
        git config --global user.name 'Niklas Reimer'
        git config --global user.email 'nr23730@users.noreply.github.com'

    - name: Update repository
      run: ./update.sh
